# Generated by Django 5.1.6 on 2025-03-19 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("Employee_id", models.CharField(max_length=20)),
                ("Employee_name", models.CharField(max_length=100)),
                ("Employee_email", models.EmailField(max_length=254)),
                ("Employee_contace", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
