# Generated by Django 5.1.6 on 2025-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="Employee_contace",
        ),
        migrations.AddField(
            model_name="employee",
            name="Employee_address",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="Employee_contact",
            field=models.CharField(default=123123123, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="Employee_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="Employee_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
